FROM node:22-alpine
RUN corepack enable pnpm
WORKDIR /app

COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile

ENV WATCHPACK_POLLING=true
ENV NEXT_TELEMETRY_DISABLED=1
EXPOSE 3001
